/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Processus.PI;
/**
 *
 * @author Rémi
 */
public class form_modifier_poi extends javax.swing.JFrame {

    /**
     * Creates new form form_modifier_poi
     */
    public form_modifier_poi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pan_md_poi = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        bouton_libelle = new javax.swing.JLabel();
        label_texte_court = new javax.swing.JLabel();
        label_description = new javax.swing.JLabel();
        bouton_modifier = new javax.swing.JButton();
        bouton_supprimer = new javax.swing.JButton();
        bouton_parcourir = new javax.swing.JButton();
        text_image = new javax.swing.JTextField();
        label_image = new javax.swing.JLabel();
        boutton_annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modification du P.I");

        bouton_libelle.setText("Libelle");

        label_texte_court.setText("Texte court");

        label_description.setText("Description");

        bouton_modifier.setText("Modifier");
        bouton_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_modifierActionPerformed(evt);
            }
        });

        bouton_supprimer.setText("Supprimer");
        bouton_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_supprimerActionPerformed(evt);
            }
        });

        bouton_parcourir.setText("Parcourir les dossiers");
        bouton_parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_parcourirActionPerformed(evt);
            }
        });

        text_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_imageActionPerformed(evt);
            }
        });

        label_image.setText("Image");

        boutton_annuler.setText("Annuler");
        boutton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_md_poiLayout = new javax.swing.GroupLayout(pan_md_poi);
        pan_md_poi.setLayout(pan_md_poiLayout);
        pan_md_poiLayout.setHorizontalGroup(
            pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_md_poiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_md_poiLayout.createSequentialGroup()
                        .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pan_md_poiLayout.createSequentialGroup()
                                .addComponent(bouton_libelle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_md_poiLayout.createSequentialGroup()
                                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_texte_court)
                                    .addComponent(label_description))
                                .addGap(34, 34, 34)
                                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_md_poiLayout.createSequentialGroup()
                        .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pan_md_poiLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label_image)
                                .addGap(26, 26, 26)
                                .addComponent(text_image, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_md_poiLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(bouton_modifier)
                                .addGap(77, 77, 77)
                                .addComponent(bouton_supprimer)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bouton_parcourir)
                            .addComponent(boutton_annuler))
                        .addGap(22, 22, 22))))
        );
        pan_md_poiLayout.setVerticalGroup(
            pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_md_poiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_libelle)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_texte_court)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_description)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_image)
                    .addComponent(bouton_parcourir))
                .addGap(18, 18, 18)
                .addGroup(pan_md_poiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_modifier)
                    .addComponent(bouton_supprimer)
                    .addComponent(boutton_annuler))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_md_poi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_md_poi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_supprimerActionPerformed
        // TODO add your handling code here:
        
        pi.Supprimer_PI(Id_PI);

    }//GEN-LAST:event_bouton_supprimerActionPerformed

    private void bouton_parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_parcourirActionPerformed
        jFileChooser1.showOpenDialog(this);
        
        String filePath = jFileChooser1.getSelectedFile().getAbsolutePath();
        text_image.setText(filePath);

    }//GEN-LAST:event_bouton_parcourirActionPerformed

    private void text_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_imageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_imageActionPerformed

    private void bouton_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_modifierActionPerformed
        // TODO add your handling code here:
    	
    	pi.Supprimer_PI(Id_PI);
    	
    }//GEN-LAST:event_bouton_modifierActionPerformed

    private void boutton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_annulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_boutton_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bouton_libelle;
    public javax.swing.JButton bouton_modifier;
    public javax.swing.JButton bouton_parcourir;
    private javax.swing.JButton bouton_supprimer;
    private javax.swing.JButton boutton_annuler;
    private javax.swing.JFileChooser jFileChooser1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JLabel label_description;
    public javax.swing.JLabel label_image;
    public javax.swing.JLabel label_texte_court;
    private javax.swing.JPanel pan_md_poi;
    public javax.swing.JTextField text_image;
    public int Id_PI;
    private PI pi = new PI();
    // End of variables declaration//GEN-END:variables
}
